Repository WSU-4110/uniq-quiz, pull requests merged in 2025-02, with the labels that each got.

#37 Controllers for deck and card completed. Add .env and readme, delete .idea
  .env.sample
  .gitignore
  INSTALLATION.md
  README.md
  client/src/index.js
  client/src/reportWebVitals.js
  package-lock.json
  server/.idea/.gitignore
  server/.idea/jsLibraryMappings.xml
  server/.idea/modules.xml
  server/.idea/runConfigurations/bin_www.xml
  server/.idea/server.iml
  server/.idea/vcs.xml
  server/app.js
  server/bin/www
  server/contollers/cardsController.js
  server/contollers/decksContoller.js
  server/package-lock.json
  server/public/index.html
  server/public/stylesheets/style.css
Labels: sprint#1

#38 Added basic authentication logic
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Home.jsx
  client/src/components/Signup.jsx
  server/app.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
Labels: functional, sprint#1

#42 Added front-end login and signup pages with stylesheet
  client/package-lock.json
  client/package.json
  client/src/App.css.old
  client/src/App.js
  client/src/Stylesheets/Auth/Auth.css
  client/src/components/Home.jsx
  client/src/components/Signup.jsx
  client/src/pages/Auth/Login.jsx
  client/src/pages/Auth/Signup.jsx
Labels: feature, functional, sprint#1

#44 Navbar
  INSTALLATION.md
  client/package-lock.json
  client/package.json
  client/public/search-icon.png
  client/src/App.js
  client/src/global/Navbar.jsx
  client/src/global/StyledButton.jsx
  client/src/global/burger-menu.svg
  client/src/index.js
  client/src/pages/Decks/Decks.jsx
  client/src/pages/Home/Home.jsx
  package-lock.json
  package.json
Labels: functional, sprint#1

#45 Added decks and cards
  INSTALLATION.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/ListItem.jsx
  client/src/global/Navbar.jsx
  client/src/global/TabButton.jsx
  client/src/pages/Cards.jsx
  client/src/pages/Decks.jsx
  client/src/pages/Decks/Decks.jsx
  client/src/pages/Home/Home.jsx
  package-lock.json
  package.json
  server/.env.sample
  server/app.js
  server/controllers/cardsController.js
  server/controllers/decksController.js
  server/package-lock.json
  server/routes/cardsRouter.js
  server/supabase.js
Labels: functional, sprint#1

#46 Quick frontend patch
  client/src/App.js
  client/src/components/Home.jsx
  client/src/global/Navbar.jsx
  client/src/pages/Auth/UserSettings.jsx
  client/src/pages/Decks/Cards.jsx
  client/src/pages/Decks/Decks.jsx
  client/src/pages/Game/Host.jsx
  client/src/pages/Game/Join.jsx
  server/.env.sample
  server/controllers/authController.js
  server/routes/authRouter.js
  server/supabaseAdmin.js
Labels: bug, functional, sprint#1

#49 Sign-up now automatically creates info in Users table, as well as Auth table
  server/controllers/authController.js
Labels: feature, functional, sprint#1, sprint#2

#50 CSS standardization and routes now check for auth
  INSTALLATION.md
  client/package-lock.json
  client/public/Logo.svg
  client/public/TitleLogo.svg
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css.old
  client/src/App.js
  client/src/Stylesheets/Auth/Auth.css
  client/src/Stylesheets/Components/ListItem.module.css
  client/src/Stylesheets/Components/Navbar.module.css
  client/src/Stylesheets/Components/ProfileBanner.module.css
  client/src/Stylesheets/Decks/Cards.module.css
  client/src/Stylesheets/Decks/Decks.module.css
  client/src/Stylesheets/Home/Landing.module.css
  client/src/components/ListItem.jsx
  client/src/components/Navbar.jsx
  client/src/components/ProfileBanner.jsx
  client/src/components/TabButton.jsx
  client/src/context/AuthContext.jsx
  client/src/global/Navbar.jsx
  client/src/global/StyledButton.jsx
  client/src/global/burger-menu.svg
  client/src/index.css
  client/src/index.js
  client/src/pages/Auth/Login.jsx
  client/src/pages/Auth/Signup.jsx
  client/src/pages/Decks/Cards.jsx
  client/src/pages/Decks/Decks.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/Home/Landing.jsx
  server/app.js
  server/controllers/authController.js
  server/routes/authRouter.js
Labels: sprint#2
